-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

REVOKE ALL ON TABLE public.tracks FROM anon;
REVOKE ALL ON TABLE public.tracks FROM authenticated;
REVOKE ALL ON TABLE public.tracks FROM postgres;
REVOKE ALL ON TABLE public.tracks FROM service_role;
REVOKE ALL ON TABLE public.tracks FROM supabase_admin;
GRANT ALL ON TABLE public.tracks TO anon;

GRANT ALL ON TABLE public.tracks TO postgres;

GRANT ALL ON TABLE public.tracks TO supabase_admin;

GRANT ALL ON TABLE public.tracks TO authenticated;

GRANT ALL ON TABLE public.tracks TO service_role;

REVOKE ALL ON TABLE public.cars FROM anon;
REVOKE ALL ON TABLE public.cars FROM authenticated;
REVOKE ALL ON TABLE public.cars FROM postgres;
REVOKE ALL ON TABLE public.cars FROM service_role;
REVOKE ALL ON TABLE public.cars FROM supabase_admin;
GRANT ALL ON TABLE public.cars TO anon;

GRANT ALL ON TABLE public.cars TO postgres;

GRANT ALL ON TABLE public.cars TO supabase_admin;

GRANT ALL ON TABLE public.cars TO authenticated;

GRANT ALL ON TABLE public.cars TO service_role;
